export const THAI_ITEMS = [
  { id: 'consonant_01_ko_kai', glyph: 'ก', category: 'consonant', thaiName: 'กอ ไก่', romanizedName: 'ko kai', audioText: 'กอ ไก่', modelFile: 'Thai Letters_OBJ/1- Go Gai.obj', unlockTier: 1, confuserGroup: 'mid_consonants' },
  { id: 'consonant_02_kho_khai', glyph: 'ข', category: 'consonant', thaiName: 'ขอ ไข่', romanizedName: 'kho khai', audioText: 'ขอ ไข่', modelFile: 'Thai Letters_OBJ/2- Ko Kai.obj', unlockTier: 1, confuserGroup: 'high_kh' },
  { id: 'consonant_03_kho_khuat', glyph: 'ฃ', category: 'consonant', thaiName: 'ขอ ขวด', romanizedName: 'kho khuat', audioText: 'ขอ ขวด', modelFile: 'Thai Letters_OBJ/3- Ko Kuad.obj', unlockTier: 3, confuserGroup: 'high_kh' },
  { id: 'consonant_04_kho_khwai', glyph: 'ค', category: 'consonant', thaiName: 'คอ ควาย', romanizedName: 'kho khwai', audioText: 'คอ ควาย', modelFile: 'Thai Letters_OBJ/4- Ko Kwai.obj', unlockTier: 2, confuserGroup: 'low_kh' },
  { id: 'consonant_05_kho_khon', glyph: 'ฅ', category: 'consonant', thaiName: 'คอ คน', romanizedName: 'kho khon', audioText: 'คอ คน', modelFile: 'Thai Letters_OBJ/5- Ko Kon.obj', unlockTier: 3, confuserGroup: 'low_kh' },
  { id: 'consonant_06_kho_rakhang', glyph: 'ฆ', category: 'consonant', thaiName: 'คอ ระฆัง', romanizedName: 'kho rakhang', audioText: 'คอ ระฆัง', modelFile: 'Thai Letters_OBJ/6- Ko Rakan.obj', unlockTier: 3, confuserGroup: 'low_kh' },
  { id: 'consonant_07_ngo_ngu', glyph: 'ง', category: 'consonant', thaiName: 'งอ งู', romanizedName: 'ngo ngu', audioText: 'งอ งู', modelFile: 'Thai Letters_OBJ/7- Ngo Nguu.obj', unlockTier: 1, confuserGroup: 'nasals' },
  { id: 'consonant_08_cho_chan', glyph: 'จ', category: 'consonant', thaiName: 'จอ จาน', romanizedName: 'cho chan', audioText: 'จอ จาน', modelFile: 'Thai Letters_OBJ/8- Jo Jaan.obj', unlockTier: 1, confuserGroup: 'ch_j' },
  { id: 'consonant_09_cho_ching', glyph: 'ฉ', category: 'consonant', thaiName: 'ฉอ ฉิ่ง', romanizedName: 'cho ching', audioText: 'ฉอ ฉิ่ง', modelFile: 'Thai Letters_OBJ/9- Cho Chin.obj', unlockTier: 2, confuserGroup: 'ch_j' },
  { id: 'consonant_10_cho_chang', glyph: 'ช', category: 'consonant', thaiName: 'ชอ ช้าง', romanizedName: 'cho chang', audioText: 'ชอ ช้าง', modelFile: 'Thai Letters_OBJ/10- Cho Chaan.obj', unlockTier: 2, confuserGroup: 'ch_j' },
  { id: 'consonant_11_so_so', glyph: 'ซ', category: 'consonant', thaiName: 'ซอ โซ่', romanizedName: 'so so', audioText: 'ซอ โซ่', modelFile: 'Thai Letters_OBJ/11- So Soo.obj', unlockTier: 2, confuserGroup: 's' },
  { id: 'consonant_12_cho_choe', glyph: 'ฌ', category: 'consonant', thaiName: 'ชอ เฌอ', romanizedName: 'cho choe', audioText: 'ชอ เฌอ', modelFile: 'Thai Letters_OBJ/12- Cho Che.obj', unlockTier: 3, confuserGroup: 'ch_j' },
  { id: 'consonant_13_yo_ying', glyph: 'ญ', category: 'consonant', thaiName: 'ยอ หญิง', romanizedName: 'yo ying', audioText: 'ยอ หญิง', modelFile: 'Thai Letters_OBJ/13- Yo Puyin.obj', unlockTier: 3, confuserGroup: 'y' },
  { id: 'consonant_14_do_chada', glyph: 'ฎ', category: 'consonant', thaiName: 'ดอ ชฎา', romanizedName: 'do chada', audioText: 'ดอ ชฎา', modelFile: 'Thai Letters_OBJ/14- Do Chada.obj', unlockTier: 4, confuserGroup: 'd_t' },
  { id: 'consonant_15_to_patak', glyph: 'ฏ', category: 'consonant', thaiName: 'ตอ ปฏัก', romanizedName: 'to patak', audioText: 'ตอ ปฏัก', modelFile: 'Thai Letters_OBJ/15- To Patag.obj', unlockTier: 4, confuserGroup: 'd_t' },
  { id: 'consonant_16_tho_than', glyph: 'ฐ', category: 'consonant', thaiName: 'ถอ ฐาน', romanizedName: 'tho than', audioText: 'ถอ ฐาน', modelFile: 'Thai Letters_OBJ/16- To Taan.obj', unlockTier: 4, confuserGroup: 'th' },
  { id: 'consonant_17_tho_montho', glyph: 'ฑ', category: 'consonant', thaiName: 'ทอ มณโฑ', romanizedName: 'tho montho', audioText: 'ทอ มณโฑ', modelFile: 'Thai Letters_OBJ/17- To Monto.obj', unlockTier: 4, confuserGroup: 'th' },
  { id: 'consonant_18_tho_phuthao', glyph: 'ฒ', category: 'consonant', thaiName: 'ทอ ผู้เฒ่า', romanizedName: 'tho phuthao', audioText: 'ทอ ผู้เฒ่า', modelFile: 'Thai Letters_OBJ/18- To Putao.obj', unlockTier: 4, confuserGroup: 'th' },
  { id: 'consonant_19_no_nen', glyph: 'ณ', category: 'consonant', thaiName: 'นอ เณร', romanizedName: 'no nen', audioText: 'นอ เณร', modelFile: 'Thai Letters_OBJ/19- No Neen.obj', unlockTier: 4, confuserGroup: 'nasals' },
  { id: 'consonant_20_do_dek', glyph: 'ด', category: 'consonant', thaiName: 'ดอ เด็ก', romanizedName: 'do dek', audioText: 'ดอ เด็ก', modelFile: 'Thai Letters_OBJ/20- Do Deg.obj', unlockTier: 1, confuserGroup: 'd_t' },
  { id: 'consonant_21_to_tao', glyph: 'ต', category: 'consonant', thaiName: 'ตอ เต่า', romanizedName: 'to tao', audioText: 'ตอ เต่า', modelFile: 'Thai Letters_OBJ/21- To Tau.obj', unlockTier: 1, confuserGroup: 'd_t' },
  { id: 'consonant_22_tho_thung', glyph: 'ถ', category: 'consonant', thaiName: 'ถอ ถุง', romanizedName: 'tho thung', audioText: 'ถอ ถุง', modelFile: 'Thai Letters_OBJ/22- To Tung.obj', unlockTier: 2, confuserGroup: 'th' },
  { id: 'consonant_23_tho_thahan', glyph: 'ท', category: 'consonant', thaiName: 'ทอ ทหาร', romanizedName: 'tho thahan', audioText: 'ทอ ทหาร', modelFile: 'Thai Letters_OBJ/23- To Tahan.obj', unlockTier: 2, confuserGroup: 'th' },
  { id: 'consonant_24_tho_thong', glyph: 'ธ', category: 'consonant', thaiName: 'ทอ ธง', romanizedName: 'tho thong', audioText: 'ทอ ธง', modelFile: 'Thai Letters_OBJ/24- To Tong.obj', unlockTier: 3, confuserGroup: 'th' },
  { id: 'consonant_25_mo_ma', glyph: 'ม', category: 'consonant', thaiName: 'มอ ม้า', romanizedName: 'mo ma', audioText: 'มอ ม้า', modelFile: 'Thai Letters_OBJ/25- Mo Maa.obj', unlockTier: 1, confuserGroup: 'nasals' },
  { id: 'consonant_26_bo_baimai', glyph: 'บ', category: 'consonant', thaiName: 'บอ ใบไม้', romanizedName: 'bo baimai', audioText: 'บอ ใบไม้', modelFile: 'Thai Letters_OBJ/26- Bo Bai Mai.obj', unlockTier: 1, confuserGroup: 'b_p' },
  { id: 'consonant_27_po_pla', glyph: 'ป', category: 'consonant', thaiName: 'ปอ ปลา', romanizedName: 'po pla', audioText: 'ปอ ปลา', modelFile: 'Thai Letters_OBJ/27- Po Pla.obj', unlockTier: 1, confuserGroup: 'b_p' },
  { id: 'consonant_28_pho_phueng', glyph: 'ผ', category: 'consonant', thaiName: 'ผอ ผึ้ง', romanizedName: 'pho phueng', audioText: 'ผอ ผึ้ง', modelFile: 'Thai Letters_OBJ/28- Po Pung.obj', unlockTier: 2, confuserGroup: 'ph_f' },
  { id: 'consonant_29_fo_fa', glyph: 'ฝ', category: 'consonant', thaiName: 'ฝอ ฝา', romanizedName: 'fo fa', audioText: 'ฝอ ฝา', modelFile: 'Thai Letters_OBJ/29- Fo Faa.obj', unlockTier: 3, confuserGroup: 'ph_f' },
  { id: 'consonant_30_pho_phan', glyph: 'พ', category: 'consonant', thaiName: 'พอ พาน', romanizedName: 'pho phan', audioText: 'พอ พาน', modelFile: 'Thai Letters_OBJ/30- Po Paan.obj', unlockTier: 2, confuserGroup: 'ph_f' },
  { id: 'consonant_31_fo_fan', glyph: 'ฟ', category: 'consonant', thaiName: 'ฟอ ฟัน', romanizedName: 'fo fan', audioText: 'ฟอ ฟัน', modelFile: 'Thai Letters_OBJ/31- Fo Fan.obj', unlockTier: 2, confuserGroup: 'ph_f' },
  { id: 'consonant_32_pho_samphao', glyph: 'ภ', category: 'consonant', thaiName: 'พอ สำเภา', romanizedName: 'pho samphao', audioText: 'พอ สำเภา', modelFile: 'Thai Letters_OBJ/32- Po San Pao.obj', unlockTier: 3, confuserGroup: 'ph_f' },
  { id: 'consonant_33_no_nu', glyph: 'น', category: 'consonant', thaiName: 'นอ หนู', romanizedName: 'no nu', audioText: 'นอ หนู', modelFile: 'Thai Letters_OBJ/33- No Nee.obj', unlockTier: 1, confuserGroup: 'nasals' },
  { id: 'consonant_34_yo_yak', glyph: 'ย', category: 'consonant', thaiName: 'ยอ ยักษ์', romanizedName: 'yo yak', audioText: 'ยอ ยักษ์', modelFile: 'Thai Letters_OBJ/34- Yo Yag.obj', unlockTier: 1, confuserGroup: 'y' },
  { id: 'consonant_35_ro_ruea', glyph: 'ร', category: 'consonant', thaiName: 'รอ เรือ', romanizedName: 'ro ruea', audioText: 'รอ เรือ', modelFile: 'Thai Letters_OBJ/35- Ro Rua.obj', unlockTier: 2, confuserGroup: 'r_l' },
  { id: 'consonant_36_lo_ling', glyph: 'ล', category: 'consonant', thaiName: 'ลอ ลิง', romanizedName: 'lo ling', audioText: 'ลอ ลิง', modelFile: 'Thai Letters_OBJ/36- Lo Ling.obj', unlockTier: 2, confuserGroup: 'r_l' },
  { id: 'consonant_37_wo_waen', glyph: 'ว', category: 'consonant', thaiName: 'วอ แหวน', romanizedName: 'wo waen', audioText: 'วอ แหวน', modelFile: 'Thai Letters_OBJ/37- Wo Weng.obj', unlockTier: 2, confuserGroup: 'w' },
  { id: 'consonant_38_so_sala', glyph: 'ศ', category: 'consonant', thaiName: 'สอ ศาลา', romanizedName: 'so sala', audioText: 'สอ ศาลา', modelFile: 'Thai Letters_OBJ/38- So Sala.obj', unlockTier: 4, confuserGroup: 's' },
  { id: 'consonant_39_so_ruesi', glyph: 'ษ', category: 'consonant', thaiName: 'สอ ฤๅษี', romanizedName: 'so ruesi', audioText: 'สอ ฤๅษี', modelFile: 'Thai Letters_OBJ/39- So Rusi.obj', unlockTier: 4, confuserGroup: 's' },
  { id: 'consonant_40_so_suea', glyph: 'ส', category: 'consonant', thaiName: 'สอ เสือ', romanizedName: 'so suea', audioText: 'สอ เสือ', modelFile: 'Thai Letters_OBJ/40- So Sua.obj', unlockTier: 1, confuserGroup: 's' },
  { id: 'consonant_41_ho_hip', glyph: 'ห', category: 'consonant', thaiName: 'หอ หีบ', romanizedName: 'ho hip', audioText: 'หอ หีบ', modelFile: 'Thai Letters_OBJ/41- Ho Hib.obj', unlockTier: 2, confuserGroup: 'h' },
  { id: 'consonant_42_lo_chula', glyph: 'ฬ', category: 'consonant', thaiName: 'ฬอ จุฬา', romanizedName: 'lo chula', audioText: 'ฬอ จุฬา', modelFile: 'Thai Letters_OBJ/42- Lo Chula.obj', unlockTier: 4, confuserGroup: 'r_l' },
  { id: 'consonant_43_o_ang', glyph: 'อ', category: 'consonant', thaiName: 'ออ อ่าง', romanizedName: 'o ang', audioText: 'ออ อ่าง', modelFile: 'Thai Letters_OBJ/43- O An.obj', unlockTier: 1, confuserGroup: 'vowel_carriers' },
  { id: 'consonant_44_ho_nokhuk', glyph: 'ฮ', category: 'consonant', thaiName: 'ฮอ นกฮูก', romanizedName: 'ho nok huk', audioText: 'ฮอ นกฮูก', modelFile: 'Thai Letters_OBJ/44- Ho Nog Hu.obj', unlockTier: 3, confuserGroup: 'h' },
  { id: 'vowel_01_group', glyph: 'ะ า', category: 'vowel', thaiName: 'สระ กลุ่ม หนึ่ง', romanizedName: 'vowels group one', audioText: 'สระ กลุ่ม หนึ่ง', modelFile: 'Thai Letters_OBJ/45- Vowels_1.obj', unlockTier: 3, confuserGroup: 'vowels' },
  { id: 'vowel_02_group', glyph: 'ิ ี', category: 'vowel', thaiName: 'สระ กลุ่ม สอง', romanizedName: 'vowels group two', audioText: 'สระ กลุ่ม สอง', modelFile: 'Thai Letters_OBJ/46- Vowels_2.obj', unlockTier: 3, confuserGroup: 'vowels' },
  { id: 'vowel_03_group', glyph: 'ึ ื', category: 'vowel', thaiName: 'สระ กลุ่ม สาม', romanizedName: 'vowels group three', audioText: 'สระ กลุ่ม สาม', modelFile: 'Thai Letters_OBJ/47- Vowels_3.obj', unlockTier: 3, confuserGroup: 'vowels' },
  { id: 'vowel_04_group', glyph: 'ุ ู', category: 'vowel', thaiName: 'สระ กลุ่ม สี่', romanizedName: 'vowels group four', audioText: 'สระ กลุ่ม สี่', modelFile: 'Thai Letters_OBJ/48- Vowels_4.obj', unlockTier: 3, confuserGroup: 'vowels' },
  { id: 'vowel_05_group', glyph: 'เ แ', category: 'vowel', thaiName: 'สระ กลุ่ม ห้า', romanizedName: 'vowels group five', audioText: 'สระ กลุ่ม ห้า', modelFile: 'Thai Letters_OBJ/49- Vowels_5.obj', unlockTier: 4, confuserGroup: 'vowels' },
  { id: 'vowel_06_group', glyph: 'โ ใ', category: 'vowel', thaiName: 'สระ กลุ่ม หก', romanizedName: 'vowels group six', audioText: 'สระ กลุ่ม หก', modelFile: 'Thai Letters_OBJ/50- Vowels_6.obj', unlockTier: 4, confuserGroup: 'vowels' },
  { id: 'vowel_07_group', glyph: 'ไ ำ', category: 'vowel', thaiName: 'สระ กลุ่ม เจ็ด', romanizedName: 'vowels group seven', audioText: 'สระ กลุ่ม เจ็ด', modelFile: 'Thai Letters_OBJ/51- Vowels_7.obj', unlockTier: 4, confuserGroup: 'vowels' },
  { id: 'symbol_52_mai_yamok', glyph: 'ๆ', category: 'symbol', thaiName: 'ไม้ยมก', romanizedName: 'mai yamok', audioText: 'ไม้ยมก', modelFile: 'Thai Letters_OBJ/52- Symbol_May Yamog.obj', unlockTier: 5, confuserGroup: 'symbols' },
  { id: 'symbol_53_paiyannoi', glyph: 'ฯ', category: 'symbol', thaiName: 'ไปยาลน้อย', romanizedName: 'paiyannoi', audioText: 'ไปยาลน้อย', modelFile: 'Thai Letters_OBJ/53- Symbol_Pai Yaan Noi.obj', unlockTier: 5, confuserGroup: 'symbols' },
  { id: 'symbol_54_lakkhangyao', glyph: 'ๅ', category: 'symbol', thaiName: 'ลากข้างยาว', romanizedName: 'lakkhangyao', audioText: 'ลากข้างยาว', modelFile: 'Thai Letters_OBJ/54- Symbol_Laag Kaan Yao.obj', unlockTier: 5, confuserGroup: 'symbols' },
  { id: 'symbol_55_rue', glyph: 'ฤ', category: 'symbol', thaiName: 'ฤ', romanizedName: 'rue', audioText: 'ฤ', modelFile: 'Thai Letters_OBJ/55- Symbol_Reu.obj', unlockTier: 5, confuserGroup: 'symbols' },
  { id: 'symbol_56_lue', glyph: 'ฦ', category: 'symbol', thaiName: 'ฦ', romanizedName: 'lue', audioText: 'ฦ', modelFile: 'Thai Letters_OBJ/56- Symbol_Leu.obj', unlockTier: 5, confuserGroup: 'symbols' },
  { id: 'tone_57_marks', glyph: '่ ้ ๊ ๋', category: 'tone', thaiName: 'วรรณยุกต์', romanizedName: 'tone marks', audioText: 'วรรณยุกต์', modelFile: 'Thai Letters_OBJ/57- Tone Marks.obj', unlockTier: 5, confuserGroup: 'tones' },
  { id: 'number_58_zero', glyph: '๐', category: 'number', thaiName: 'เลข ศูนย์', romanizedName: 'zero', audioText: 'เลข ศูนย์', modelFile: 'Thai Letters_OBJ/58- Number_0.obj', unlockTier: 1, confuserGroup: 'numbers' },
  { id: 'number_59_one', glyph: '๑', category: 'number', thaiName: 'เลข หนึ่ง', romanizedName: 'one', audioText: 'เลข หนึ่ง', modelFile: 'Thai Letters_OBJ/59- Number_1.obj', unlockTier: 1, confuserGroup: 'numbers' },
  { id: 'number_60_two', glyph: '๒', category: 'number', thaiName: 'เลข สอง', romanizedName: 'two', audioText: 'เลข สอง', modelFile: 'Thai Letters_OBJ/60- Number_2.obj', unlockTier: 1, confuserGroup: 'numbers' },
  { id: 'number_61_three', glyph: '๓', category: 'number', thaiName: 'เลข สาม', romanizedName: 'three', audioText: 'เลข สาม', modelFile: 'Thai Letters_OBJ/61- Number_3.obj', unlockTier: 1, confuserGroup: 'numbers' },
  { id: 'number_62_four', glyph: '๔', category: 'number', thaiName: 'เลข สี่', romanizedName: 'four', audioText: 'เลข สี่', modelFile: 'Thai Letters_OBJ/62- Number_4.obj', unlockTier: 1, confuserGroup: 'numbers' },
  { id: 'number_63_five', glyph: '๕', category: 'number', thaiName: 'เลข ห้า', romanizedName: 'five', audioText: 'เลข ห้า', modelFile: 'Thai Letters_OBJ/63- Number_5.obj', unlockTier: 1, confuserGroup: 'numbers' },
  { id: 'number_64_six', glyph: '๖', category: 'number', thaiName: 'เลข หก', romanizedName: 'six', audioText: 'เลข หก', modelFile: 'Thai Letters_OBJ/64- Number_6.obj', unlockTier: 2, confuserGroup: 'numbers' },
  { id: 'number_65_seven', glyph: '๗', category: 'number', thaiName: 'เลข เจ็ด', romanizedName: 'seven', audioText: 'เลข เจ็ด', modelFile: 'Thai Letters_OBJ/65- Number_7.obj', unlockTier: 2, confuserGroup: 'numbers' },
  { id: 'number_66_eight', glyph: '๘', category: 'number', thaiName: 'เลข แปด', romanizedName: 'eight', audioText: 'เลข แปด', modelFile: 'Thai Letters_OBJ/66- Number_8.obj', unlockTier: 2, confuserGroup: 'numbers' },
  { id: 'number_67_nine', glyph: '๙', category: 'number', thaiName: 'เลข เก้า', romanizedName: 'nine', audioText: 'เลข เก้า', modelFile: 'Thai Letters_OBJ/67- Number_9.obj', unlockTier: 2, confuserGroup: 'numbers' },
];

export const THAI_BY_ID = Object.fromEntries(THAI_ITEMS.map((item) => [item.id, item]));

export function getUnlockedItems(tier) {
  return THAI_ITEMS.filter((item) => item.unlockTier <= tier);
}

export function audioPathFor(item) {
  return `assets/audio/thai/${item.id}.wav`;
}
