// ==========================================
// Voidloop — Zone Definitions
// 7 zones covering all 26 letters A-Z
// ==========================================

export const ZONES = [
  {
    id: 'forest',
    name: 'Whispering Forest',
    order: 1,
    description: 'A peaceful forest with basic blocks and goblins.',
    letters: ['A', 'B', 'C', 'D'],
    blockTypes: ['grass', 'dirt', 'stone', 'wood'],
    floatingBlockTypes: ['mossy_stone', 'forest_crystal', 'amber_ore', 'ancient_wood'],
    enemyTypes: ['goblin', 'slime'],
    fogColor: 0x87ceeb,
    fogNear: 20,
    fogFar: 45,
    bounds: { minX: -60, maxX: 0, minZ: -60, maxZ: 60 },
    spawnPoint: { x: -30, z: 0 },
    exitGateway: { x: -2, z: 0, targetZone: 'fire' },
    hazard: null,
    structures: {
      trees: ['birch', 'oak'],
      treeDensity: 0.055,
      decorations: ['tall_grass', 'flower_red', 'flower_yellow', 'mushroom'],
      decorDensity: 0.12,
      boulders: true,
      boulderDensity: 0.015,
    },
    pickaxeId: null,
    suitId: null,
    staffId: null,
    fluidBodies: [
      {
        id: 'forest_pond',
        type: 'water',
        x: -42,
        z: 14,
        radiusX: 8,
        radiusZ: 6,
        surfaceY: 1.15,
        bottomY: -1.8,
        safe: true,
        tint: 0x2bb8a6,
        foamColor: 0xd8fff7,
      },
    ],
  },
  {
    id: 'fire',
    name: 'Ember Wastes',
    order: 2,
    description: 'A scorched landscape. Fire blocks require special gear.',
    letters: ['E', 'F', 'G', 'H'],
    blockTypes: ['stone_dark', 'coal', 'brick', 'stone_dark'],
    floatingBlockTypes: ['scorched_rock', 'magma_crystal', 'obsidian', 'ember_core'],
    enemyTypes: ['demon', 'bat'],
    fogColor: 0x2a1a1a,
    fogNear: 14,
    fogFar: 35,
    bounds: { minX: 0, maxX: 60, minZ: -60, maxZ: 60 },
    spawnPoint: { x: 10, z: 0 },
    exitGateway: { x: 58, z: 0, targetZone: 'ice' },
    hazard: {
      type: 'burn',
      damagePerSecond: 5,
      mitigationItem: 'fire_suit',
    },
    structures: {
      trees: ['dark_oak'],
      treeDensity: 0.025,
      decorations: ['dead_bush'],
      decorDensity: 0.06,
      boulders: true,
      boulderDensity: 0.03,
    },
    fluidBodies: [
      {
        id: 'ember_lava_pool',
        type: 'lava',
        x: 26,
        z: -18,
        radiusX: 7,
        radiusZ: 5,
        surfaceY: 0.95,
        bottomY: -2.4,
      },
      {
        id: 'ember_lava_channel',
        type: 'lava',
        x: 42,
        z: 18,
        radiusX: 9,
        radiusZ: 4,
        surfaceY: 0.9,
        bottomY: -2.2,
      },
    ],
    pickaxeId: null,
    suitId: 'fire_suit',
    staffId: null,
  },
  {
    id: 'ice',
    name: 'Frostpeak',
    order: 3,
    description: 'A frozen wasteland of ice and snow.',
    letters: ['I', 'J', 'K', 'L'],
    blockTypes: ['ice', 'snow', 'stone', 'water'],
    floatingBlockTypes: ['packed_ice', 'frost_crystal', 'glacial_ore', 'blizzard_core'],
    enemyTypes: ['yeti', 'bat'],
    fogColor: 0xaaddff,
    fogNear: 16,
    fogFar: 40,
    bounds: { minX: -60, maxX: 60, minZ: -180, maxZ: -60 },
    spawnPoint: { x: 0, z: -120 },
    exitGateway: { x: 0, z: -62, targetZone: 'desert' },
    hazard: {
      type: 'freeze',
      slowdownPercent: 30,
      mitigationItem: 'ice_suit',
    },
    structures: {
      trees: ['spruce'],
      treeDensity: 0.04,
      decorations: [],
      decorDensity: 0.0,
      boulders: true,
      boulderDensity: 0.025,
    },
    pickaxeId: null,
    suitId: 'ice_suit',
    staffId: null,
  },
  {
    id: 'desert',
    name: 'Sandscape',
    order: 4,
    description: 'A scorching desert with sand dunes and hidden treasures.',
    letters: ['M', 'N', 'O', 'P'],
    blockTypes: ['sand_A', 'sand_B', 'stone', 'brick'],
    floatingBlockTypes: ['sandstone_block', 'desert_crystal', 'desert_gold_ore', 'sun_core'],
    enemyTypes: ['skeleton', 'bat'],
    fogColor: 0xe6c288,
    fogNear: 18,
    fogFar: 42,
    bounds: { minX: -60, maxX: 60, minZ: 60, maxZ: 180 },
    spawnPoint: { x: 0, z: 120 },
    exitGateway: { x: 0, z: 62, targetZone: 'steelworks' },
    hazard: {
      type: 'heat',
      staminaDrainPerSecond: 10,
      mitigationItem: 'desert_suit',
    },
    structures: {
      trees: ['acacia', 'cactus'],
      treeDensity: 0.035,
      decorations: ['dead_bush'],
      decorDensity: 0.05,
      boulders: true,
      boulderDensity: 0.02,
    },
    pickaxeId: null,
    suitId: 'desert_suit',
    staffId: null,
  },
  {
    id: 'steelworks',
    name: 'Steelworks',
    order: 5,
    description: 'An industrial factory of gears and molten metal.',
    letters: ['Q', 'R', 'S', 'T'],
    blockTypes: ['prototype', 'metal', 'stone_dark', 'gravel'],
    floatingBlockTypes: ['rusted_scrap', 'factory_crystal', 'alloy_ore', 'furnace_core'],
    enemyTypes: ['soldier', 'bat'],
    fogColor: 0x4a5568,
    fogNear: 14,
    fogFar: 35,
    bounds: { minX: 60, maxX: 180, minZ: -60, maxZ: 60 },
    spawnPoint: { x: 120, z: 0 },
    exitGateway: { x: 62, z: 0, targetZone: 'mire' },
    hazard: {
      type: 'toxic',
      damagePerSecond: 4,
      mitigationItem: 'ventilator_suit',
    },
    structures: {
      trees: [],
      treeDensity: 0.0,
      decorations: [],
      decorDensity: 0.0,
      boulders: true,
      boulderDensity: 0.04,
    },
    pickaxeId: null,
    suitId: 'ventilator_suit',
    staffId: null,
  },
  {
    id: 'mire',
    name: 'Mire',
    order: 6,
    description: 'A murky swamp of mud and ancient trees.',
    letters: ['U', 'V', 'W', 'X'],
    blockTypes: ['dirt', 'wood', 'water', 'gravel'],
    floatingBlockTypes: ['mud_clump', 'moss_crystal', 'petrified_log', 'heart_of_the_mire'],
    enemyTypes: ['zombie', 'bat'],
    fogColor: 0x5a7a5a,
    fogNear: 15,
    fogFar: 38,
    bounds: { minX: 60, maxX: 180, minZ: -180, maxZ: -60 },
    spawnPoint: { x: 120, z: -120 },
    exitGateway: { x: 120, z: -62, targetZone: 'citadel' },
    hazard: null,
    structures: {
      trees: ['dark_oak'],
      treeDensity: 0.03,
      decorations: ['mushroom', 'tall_grass'],
      decorDensity: 0.08,
      boulders: true,
      boulderDensity: 0.015,
    },
    pickaxeId: null,
    suitId: 'wading_boots',
    staffId: null,
  },
  {
    id: 'citadel',
    name: 'Citadel',
    order: 7,
    description: 'A grand castle of stone and gold. The final challenge.',
    letters: ['Y', 'Z'],
    blockTypes: ['bricks_A', 'bricks_B', 'stone', 'stone_dark'],
    floatingBlockTypes: ['castle_brick', 'royal_crystal', 'citadel_gold_ore', 'crown_core'],
    enemyTypes: ['skeleton', 'demon'],
    fogColor: 0xd4a574,
    fogNear: 18,
    fogFar: 42,
    bounds: { minX: 60, maxX: 180, minZ: 60, maxZ: 180 },
    spawnPoint: { x: 120, z: 120 },
    exitGateway: null,
    hazard: {
      type: 'curse',
      stunChancePerSecond: 0.1,
      mitigationItem: 'royal_shield',
    },
    structures: {
      trees: [],
      treeDensity: 0.0,
      decorations: [],
      decorDensity: 0.0,
      boulders: false,
      boulderDensity: 0.0,
    },
    pickaxeId: null,
    suitId: 'royal_shield',
    staffId: null,
  },
];

export function getZoneById(id) {
  return ZONES.find(z => z.id === id);
}

export function getZoneAtPosition(x, z) {
  for (const zone of ZONES) {
    const b = zone.bounds;
    if (x >= b.minX && x < b.maxX && z >= b.minZ && z < b.maxZ) {
      return zone;
    }
  }
  return null;
}
